services:  

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_image
    container_name: backend_container
    restart: always
    environment:
      - DB_HOST_NAME=postgres_container
      - DATABASE_PORT=5432
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=postgres
      - DB_USER=postgres
      - CLOUDMERSIVE_API_KEY=${CLOUDMERSIVE_API_KEY}
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
 
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
     - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"


volumes:
  postgres-db:
  app: